pre-commit:
  parallel: true
  commands:
    oxlint:
      glob: "*.{js,ts,jsx,tsx}"
      run: bunx oxlint --fix {staged_files}
      stage_fixed: true
    typecheck:
      run: bunx --bun tsgo --noEmit
    test:
      run: bun test --pass-with-no-tests
