// AUTO-GENERATED by `env-manager ts` - do not edit
import { z } from 'zod';

const env = z
	.object({
		SERVER_SECRET: z.string(),
		SERVER_PASSWORD: z.string(),
		API_PORT: z.coerce.number().int().min(1).max(65535),
		CLIENT_PORT: z.coerce.number().int().min(1).max(65535),
		VITE_HOST: z.string(),
		OPENROUTER_API_KEY: z.string().regex(/^sk-or-v1-/),
		MARKER_PDF_GEMINI_KEY: z.string(),
		VITALS_DATA_DIR: z.string(),
		VITALS_DB_PATH: z.string(),
		AWS_REGION: z.string(),
		AWS_ACCESS_KEY_ID: z.string(),
		AWS_SECRET_ACCESS_KEY: z.string(),
		AWS_SESSION_TOKEN: z.string().optional(),
		VITALS_S3_BUCKET: z.string(),
		VITALS_S3_PREFIX: z.string(),
		AWS_PREFIX: z.string(),
		ELEVENLABS_API_KEY: z.string(),
	})
	.parse(process.env);

export default env;
